# Generated by Django 3.2.2 on 2021-06-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_auto_20210511_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='fast_sell',
            field=models.BooleanField(null=True, verbose_name='Быстрая покупка'),
        ),
    ]
