# Generated by Django 3.2.2 on 2021-06-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_bb_favorite_fruit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='favorite_fruit',
            field=models.BooleanField(null=True, verbose_name='Любимый фрукт'),
        ),
    ]
